In [1]:
import numpy as np

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [3]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


# 0-D Arrays

In [4]:
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Arrays

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D Arrays

In [8]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions

In [9]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
import numpy as np 
a = np.array([1,2,3,4,5]) 
np.save('outfile',a)

In [11]:
import numpy as np 
b = np.load('outfile.npy') 
print(b)

[1 2 3 4 5]


In [12]:
import numpy as np 

a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print(b) 

[1. 2. 3. 4. 5.]


# Indexing Using Index Arrays

In [14]:
import numpy as np
arr=np.arange(1,10,2) 
print("Elements of array: ",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ",arr1)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


# Indexing in 1 dimension

In [15]:
import numpy as np 
arr1=np.arange(4)
print("Array arr11:",arr1)
print("Element at index 0 of arri is: ", arr1[0])
print("Element at index 1 of arr1 is: ", arr1[1])

Array arr11: [0 1 2 3]
Element at index 0 of arri is:  0
Element at index 1 of arr1 is:  1


# Indexing in 2 Dimensions

In [16]:
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("Element at eth row and eth column of arr1 is:",arr1[0,0]) 
print("Element at 1st row and 2nd column of arr1 is:", arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at eth row and eth column of arr1 is: 0
Element at 1st row and 2nd column of arr1 is: 6


# Indexing in 3 Dimensions

In [17]:
import numpy as np 
arr=np.arange(12) 
arr1=arr.reshape(2,2,3) 
print("Array arr1:\n", arr1) 
print("Element:", arr1[1,0,2])

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 8


# Slicing 1D NumPy Arrays

In [18]:
import numpy as np 
arr = np.arange(6) 
print("array arr:",arr)
print("sliced element of array: ", arr[1:5])

array arr: [0 1 2 3 4 5]
sliced element of array:  [1 2 3 4]


# Slicing 2D Numpy Array

In [19]:
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1: \n",arr1)
print("\n")
print("elements of 1st row and 1st column upto last column \n", arr1[1:,1:4])

Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


elements of 1st row and 1st column upto last column 
 [[ 5  6  7]
 [ 9 10 11]]


# Broadcasting

In [20]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:') 
print(a) 
print('\n')  
   
print('Second array:') 
print(b) 
print('\n')  
   
print('First Array + Second Array' )
print( a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# Structured arrays

In [21]:
#Python program to demonstrate
# Structured array
import numpy as np
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)], 
             dtype=[('name', (np. str_, 10)), ('age', np.int32), ('weight', np.float64)])
print(a)

[('Sana', 2, 21.) ('Mansi', 7, 29.)]


# Statistical Functions

In [22]:
import numpy as np
arr = np.arange(0,10)

In [23]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Shubham\AppData\Local\Temp/ipykernel_18268/2878212635.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])